<a href="https://colab.research.google.com/github/rajabhi906856-arch/ml-project/blob/main/network_intrusion_detection_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Network Intrusion Detection System (NIDS)**

In [ ]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.13/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.13/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.13/dist-packages (from kaggle) (1.19.5)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.13/dist-packages (from kaggle) (0.1.37)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from kaggle) (26.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.13/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.13/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.13/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.13/dist-packages (from bleach->kaggle) (0.6.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (5.11.1)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.13/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->kaggle) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->kaggle) (3.19)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->kaggle) (2026.7.22)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (2.22.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.11.4)

In [ ]:
!pip install pandas numpy scikit-learn xgboost imbalanced-learn matplotlib seaborn

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (1.6.1)
Requirement already satisfied: xgboost in /usr/local/lib/python3.13/dist-packages (3.4.1)
Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.13/dist-packages (0.14.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.13/dist-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: nvidia-nccl-cu13 in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.31.2)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.6 in /usr/local/lib/python3.13/dist-packages (from imbalanced-learn) (0.1.6)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

## Table of Contents

### 1 .Project Setup

####1.1. import libraries

In [ ]:
import kagglehub
import pandas as pd
import numpy as np
import os

####1.2. mount google drive

In [2]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
save_path = "/content/drive/MyDrive/NIDS_Project/network_intrusion_combined.csv"

df.to_csv(save_path, index=False)

print("Dataset saved successfully!")

Dataset saved successfully!

###2 . Dataset Acquisition

####2.1 Download Kaggle Dataset

In [ ]:
import os
os.environ["KAGGLE_API_TOKEN"] = "export KAGGLE_API_TOKEN=KGAT_997484021e388dfbc7bccb81a15a3726"

In [ ]:
import kagglehub
path = kagglehub.dataset_download("chethuhn/network-intrusion-dataset")
print("data downloaded to:",path)

Downloading to /root/.cache/kagglehub/datasets/chethuhn/network-intrusion-dataset/1.archive...

100%|██████████| 230M/230M [00:11<00:00, 20.5MB/s]

Extracting files...

data downloaded to: /root/.cache/kagglehub/datasets/chethuhn/network-intrusion-dataset/versions/1

In [ ]:
path = kagglehub.dataset_download("chethuhn/network-intrusion-dataset")
print("Data downloaded to:", path)

Using Colab cache for faster access to the 'network-intrusion-dataset' dataset.
Data downloaded to: /kaggle/input/network-intrusion-dataset

###3 . Dataset Loading & Combining

In [ ]:
print(os.listdir(path))

['Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv', 'Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv', 'Tuesday-WorkingHours.pcap_ISCX.csv', 'Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv', 'Monday-WorkingHours.pcap_ISCX.csv', 'Friday-WorkingHours-Morning.pcap_ISCX.csv', 'Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv', 'Wednesday-workingHours.pcap_ISCX.csv']

In [ ]:
os.listdir(path)

['Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv',
 'Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv',
 'Tuesday-WorkingHours.pcap_ISCX.csv',
 'Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv',
 'Monday-WorkingHours.pcap_ISCX.csv',
 'Friday-WorkingHours-Morning.pcap_ISCX.csv',
 'Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv',
 'Wednesday-workingHours.pcap_ISCX.csv']

In [ ]:
import pandas as pd
import os

# Get all CSV files
csv_files = [f for f in os.listdir(path) if f.endswith(".csv")]

# Store individual DataFrames
dfs = []

# Load each CSV
for file in csv_files:
    print("Loading:", file)

    temp = pd.read_csv(os.path.join(path, file))

    # Remove leading/trailing spaces from column names
    temp.columns = temp.columns.str.strip()

    dfs.append(temp)

# Concatenate all CSV files
df = pd.concat(dfs, ignore_index=True)

print("\nNumber of CSV files loaded:", len(dfs))
print("Final shape:", df.shape)

Loading: Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
Loading: Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
Loading: Tuesday-WorkingHours.pcap_ISCX.csv
Loading: Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
Loading: Monday-WorkingHours.pcap_ISCX.csv
Loading: Friday-WorkingHours-Morning.pcap_ISCX.csv
Loading: Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
Loading: Wednesday-workingHours.pcap_ISCX.csv

Number of CSV files loaded: 8
Final shape: (2830743, 79)

###4 .Initial Data Exploration

In [ ]:
df.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,22,1266342,41,44,2664,6954,456,0,64.975610,109.864573,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,22,1319353,41,44,2664,6954,456,0,64.975610,109.864573,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,22,160,1,1,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,22,1303488,41,42,2728,6634,456,0,66.536585,110.129945,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,35396,77,1,2,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [ ]:
df.shape

(2830743, 79)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2830743 entries, 0 to 2830742
Data columns (total 79 columns):
 #   Column                       Dtype
---  ------                       -----
 0   Destination Port             int64
 1   Flow Duration                int64
 2   Total Fwd Packets            int64
 3   Total Backward Packets       int64
 4   Total Length of Fwd Packets  int64
 5   Total Length of Bwd Packets  int64
 6   Fwd Packet Length Max        int64
 7   Fwd Packet Length Min        int64
 8   Fwd Packet Length Mean       float64
 9   Fwd Packet Length Std        float64
 10  Bwd Packet Length Max        int64
 11  Bwd Packet Length Min        int64
 12  Bwd Packet Length Mean       float64
 13  Bwd Packet Length Std        float64
 14  Flow Bytes/s                 float64
 15  Flow Packets/s               float64
 16  Flow IAT Mean                float64
 17  Flow IAT Std                 float64
 18  Flow IAT Max                 int64
 19  Flow IAT Min                 int64
 20  Fwd IAT Total                int64
 21  Fwd IAT Mean                 float64
 22  Fwd IAT Std                  float64
 23  Fwd IAT Max                  int64
 24  Fwd IAT Min                  int64
 25  Bwd IAT Total                int64
 26  Bwd IAT Mean                 float64
 27  Bwd IAT Std                  float64
 28  Bwd IAT Max                  int64
 29  Bwd IAT Min                  int64
 30  Fwd PSH Flags                int64
 31  Bwd PSH Flags                int64
 32  Fwd URG Flags                int64
 33  Bwd URG Flags                int64
 34  Fwd Header Length            int64
 35  Bwd Header Length            int64
 36  Fwd Packets/s                float64
 37  Bwd Packets/s                float64
 38  Min Packet Length            int64
 39  Max Packet Length            int64
 40  Packet Length Mean           float64
 41  Packet Length Std            float64
 42  Packet Length Variance       float64
 43  FIN Flag Count               int64
 44  SYN Flag Count               int64
 45  RST Flag Count               int64
 46  PSH Flag Count               int64
 47  ACK Flag Count               int64
 48  URG Flag Count               int64
 49  CWE Flag Count               int64
 50  ECE Flag Count               int64
 51  Down/Up Ratio                int64
 52  Average Packet Size          float64
 53  Avg Fwd Segment Size         float64
 54  Avg Bwd Segment Size         float64
 55  Fwd Header Length.1          int64
 56  Fwd Avg Bytes/Bulk           int64
 57  Fwd Avg Packets/Bulk         int64
 58  Fwd Avg Bulk Rate            int64
 59  Bwd Avg Bytes/Bulk           int64
 60  Bwd Avg Packets/Bulk         int64
 61  Bwd Avg Bulk Rate            int64
 62  Subflow Fwd Packets          int64
 63  Subflow Fwd Bytes            int64
 64  Subflow Bwd Packets          int64
 65  Subflow Bwd Bytes            int64
 66  Init_Win_bytes_forward       int64
 67  Init_Win_bytes_backward      int64
 68  act_data_pkt_fwd             int64
 69  min_seg_size_forward         int64
 70  Active Mean                  float64
 71  Active Std                   float64
 72  Active Max                   int64
 73  Active Min                   int64
 74  Idle Mean                    float64
 75  Idle Std                     float64
 76  Idle Max                     int64
 77  Idle Min                     int64
 78  Label                        object
dtypes: float64(24), int64(54), object(1)
memory usage: 1.7+ GB

In [ ]:
print(df.columns.tolist())

['Destination Port', 'Flow Duration', 'Total Fwd Packets', 'Total Backward Packets', 'Total Length of Fwd Packets', 'Total Length of Bwd Packets', 'Fwd Packet Length Max', 'Fwd Packet Length Min', 'Fwd Packet Length Mean', 'Fwd Packet Length Std', 'Bwd Packet Length Max', 'Bwd Packet Length Min', 'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length', 'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s', 'Min Packet Length', 'Max Packet Length', 'Packet Length Mean', 'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count', 'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count', 'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio', 'Average Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size', 'Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets', 'Subflow Bwd Bytes', 'Init_Win_bytes_forward', 'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label']

In [ ]:
print(df["Label"].value_counts())

Label
BENIGN                        2273097
DoS Hulk                       231073
PortScan                       158930
DDoS                           128027
DoS GoldenEye                   10293
FTP-Patator                      7938
SSH-Patator                      5897
DoS slowloris                    5796
DoS Slowhttptest                 5499
Bot                              1966
Web Attack � Brute Force         1507
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name: count, dtype: int64

In [ ]:
df.columns = df.columns.str.strip()

In [ ]:
for col in df.columns:
    if col != col.strip():
        print(f"Whitespace issue: '{col}'")

In [ ]:
df['Flow Duration']

0          1266342
1          1319353
2              160
3          1303488
4               77
            ...
2830738      32215
2830739        324
2830740         82
2830741    1048635
2830742      94939
Name: Flow Duration, Length: 2830743, dtype: int64

In [ ]:
print("Number of CSVs loaded:", len(df))

Number of CSVs loaded: 2830743

In [ ]:
print("Number of CSVs loaded:", len(dfs))

Number of CSVs loaded: 8

In [ ]:
df.shape

(2830743, 79)

In [ ]:
print("Final shape:", df.shape)

Final shape: (2830743, 79)

In [ ]:
import os

project_path = "/content/drive/MyDrive/NIDS_Project"

os.makedirs(project_path, exist_ok=True)

print("Folder created:", project_path)

Folder created: /content/drive/MyDrive/NIDS_Project

In [ ]:
import os

print(os.path.exists(save_path))

True

In [ ]:
df.isnull().sum()

Destination Port               0
Flow Duration                  0
Total Fwd Packets              0
Total Backward Packets         0
Total Length of Fwd Packets    0
                              ..
Idle Mean                      0
Idle Std                       0
Idle Max                       0
Idle Min                       0
Label                          0
Length: 79, dtype: int64

In [ ]:
df.dtypes

Destination Port                 int64
Flow Duration                    int64
Total Fwd Packets                int64
Total Backward Packets           int64
Total Length of Fwd Packets      int64
                                ...
Idle Mean                      float64
Idle Std                       float64
Idle Max                         int64
Idle Min                         int64
Label                           object
Length: 79, dtype: object

In [ ]:
df.describe()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,...,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06
mean,8.071483e+03,1.478566e+07,9.361160e+00,1.039377e+01,5.493024e+02,1.616264e+04,2.075999e+02,1.871366e+01,5.820194e+01,6.891013e+01,...,5.418218e+00,-2.741688e+03,8.155132e+04,4.113412e+04,1.531825e+05,5.829582e+04,8.316037e+06,5.038439e+05,8.695752e+06,7.920031e+06
std,1.828363e+04,3.365374e+07,7.496728e+02,9.973883e+02,9.993589e+03,2.263088e+06,7.171848e+02,6.033935e+01,1.860912e+02,2.811871e+02,...,6.364257e+02,1.084989e+06,6.485999e+05,3.933815e+05,1.025825e+06,5.770923e+05,2.363008e+07,4.602984e+06,2.436689e+07,2.336342e+07
min,0.000000e+00,-1.300000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,-5.368707e+08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,5.300000e+01,1.550000e+02,2.000000e+00,1.000000e+00,1.200000e+01,0.000000e+00,6.000000e+00,0.000000e+00,6.000000e+00,0.000000e+00,...,0.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,8.000000e+01,3.131600e+04,2.000000e+00,2.000000e+00,6.200000e+01,1.230000e+02,3.700000e+01,2.000000e+00,3.400000e+01,0.000000e+00,...,1.000000e+00,2.400000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,4.430000e+02,3.204828e+06,5.000000e+00,4.000000e+00,1.870000e+02,4.820000e+02,8.100000e+01,3.600000e+01,5.000000e+01,2.616295e+01,...,2.000000e+00,3.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,6.553500e+04,1.200000e+08,2.197590e+05,2.919220e+05,1.290000e+07,6.554530e+08,2.482000e+04,2.325000e+03,5.940857e+03,7.125597e+03,...,2.135570e+05,1.380000e+02,1.100000e+08,7.420000e+07,1.100000e+08,1.100000e+08,1.200000e+08,7.690000e+07,1.200000e+08,1.200000e+08

###5 .Data cleaning

In [ ]:
import numpy as np
np.isinf(df.select_dtypes(include= np.number)).sum()

Destination Port               0
Flow Duration                  0
Total Fwd Packets              0
Total Backward Packets         0
Total Length of Fwd Packets    0
                              ..
Active Min                     0
Idle Mean                      0
Idle Std                       0
Idle Max                       0
Idle Min                       0
Length: 78, dtype: int64

In [ ]:
num_cols=df.select_dtypes(include=np.number).columns
neg_counts=(df[num_cols]<0).sum()
print(neg_counts)

Destination Port                 0
Flow Duration                  115
Total Fwd Packets                0
Total Backward Packets           0
Total Length of Fwd Packets      0
                              ...
Active Min                       0
Idle Mean                        0
Idle Std                         0
Idle Max                         0
Idle Min                         0
Length: 78, dtype: int64

In [ ]:
df[df['Flow Duration'] < 0]['Flow Duration']

47878     -1
61031     -1
61927     -1
86737     -1
90372     -1
          ..
2678632   -1
2742850   -1
2743589   -1
2777786   -1
2794659   -1
Name: Flow Duration, Length: 115, dtype: int64

In [ ]:
df['Flow Duration'].min()

-13

In [ ]:
df['Flow Duration'].max()

119999998

In [ ]:
df.loc[df['Flow Duration'] < 0, 'Flow Duration'].value_counts().sort_index()

Flow Duration
-13      1
-12      2
-4       1
-2       2
-1     109
Name: count, dtype: int64

In [ ]:
df[df['Flow Duration'] < 0]['Label'].value_counts()

Label
BENIGN    115
Name: count, dtype: int64

In [3]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
import pandas as pd

save_path = "/content/drive/MyDrive/NIDS_Project/network_intrusion_combined.csv"

df = pd.read_csv(save_path)

In [ ]:
df = df[df['Flow Duration'] >= 0].copy()

In [ ]:
df.loc[df['Flow Duration'] < 0, 'Flow Duration'].value_counts().sort_index()

Series([], Name: count, dtype: int64)

In [ ]:
df.duplicated().sum()

np.int64(308381)

In [ ]:
# How many duplicates per class?
dupe_rows = df[df.duplicated(keep=False)]
print(dupe_rows['Label'].value_counts())

Label
BENIGN                      236257
PortScan                    101501
DoS Hulk                     59564
SSH-Patator                   2826
FTP-Patator                   2457
DoS slowloris                  507
DoS Slowhttptest               323
Web Attack � Brute Force        62
DDoS                            20
Bot                             19
DoS GoldenEye                   14
Name: count, dtype: int64

In [ ]:
df.shape

(2830743, 79)

In [ ]:
df=df.drop_duplicates()

In [ ]:
print("After:", df.shape)

After: (2522362, 79)

In [ ]:
print(df['Label'].value_counts())

Label
BENIGN                        2096484
DoS Hulk                       172849
DDoS                           128016
PortScan                        90819
DoS GoldenEye                   10286
FTP-Patator                      5933
DoS slowloris                    5385
DoS Slowhttptest                 5228
SSH-Patator                      3219
Bot                              1953
Web Attack � Brute Force         1470
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name: count, dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.dtypes.value_counts()

int64      54
float64    24
object      1
Name: count, dtype: int64

In [8]:
df.nunique().sort_values()

Bwd PSH Flags                 1
Fwd Avg Bulk Rate             1
Bwd Avg Bytes/Bulk            1
Bwd Avg Packets/Bulk          1
Fwd Avg Packets/Bulk          1
                         ...
Bwd Packets/s           1107886
Flow IAT Mean           1166311
Fwd Packets/s           1220423
Flow Packets/s          1240164
Flow Bytes/s            1593908
Length: 79, dtype: int64

In [9]:
print(df['Label'].isnull().sum())
print(df['Label'].nunique())
print(df['Label'].value_counts())

0
15
Label
BENIGN                        2096484
DoS Hulk                       172849
DDoS                           128016
PortScan                        90819
DoS GoldenEye                   10286
FTP-Patator                      5933
DoS slowloris                    5385
DoS Slowhttptest                 5228
SSH-Patator                      3219
Bot                              1953
Web Attack � Brute Force         1470
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name: count, dtype: int64

In [10]:
constant_cols = [col for col in df.columns if df[col].nunique() <= 1]

print("Number of constant columns:", len(constant_cols))
print(constant_cols)

Number of constant columns: 8
['Bwd PSH Flags', 'Bwd URG Flags', 'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate']

In [11]:
df = df.drop(columns=constant_cols)

In [13]:
print("removed:", len(constant_cols))
print("remaining:", df.shape)

removed: 8
remaining: (2522362, 71)